server:
  port: 7002
spring:
  application:
    name: weather-city-microservice
logging:
  level:
    com.imooc.spring.cloud.weather.city.client.WeatherCityOpenClient: debug
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 20000
hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  eager-load:
    enabled: true
