server:
  port: 7000
spring:
  application:
    name: weather-collection-microservice
  redis:
    password: Sagreen2017
    host: 139.196.238.115
    database: 1
logging:
  level:
    com.imooc.spring.cloud.weather.collection.client.WeatherDataOpenClient: debug
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 20000

ribbon:
  eager-load:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: local
  cloud:
    nacos:
      discovery:
        namespace: 827b9ab9-163e-4816-a657-bc941bca42d6
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: localhost:7005