server:
  port: 7004
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: weather-data-microservice
          uri: lb://weather-data-microservice
          predicates:
            - Path=/weather/data/**
        - id: weather-city-microservice
          uri: lb://weather-city-microservice
          predicates:
            - Path=/weather/city/**
  application:
    name: weather-gateway
management:
  endpoints:
    web:
      exposure:
        include: '*'
app:
  id:
    ${spring.application.name}
apollo:
  meta:
    http://localhost:8080
  boostrap:
    enabled: true
---
spring:
  profiles: local
  cloud:
    nacos:
      discovery:
        namespace: 827b9ab9-163e-4816-a657-bc941bca42d6
        server-addr: 127.0.0.1:8848